name: Create Release

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.1.0
        env:
          GITHUB_USER: ${{ secrets.CI_NAME }}
          GITHUB_EMAIL: ${{ secrets.CI_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish NPM
        run: |
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
